package ru.chr.addressbook;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import java.util.HashMap;
import java.util.Map;

public class GroupCreationTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("http://localhost/addressbook/");
        driver.manage().window().setSize(new Dimension(1400, 700));
        login("admin", "secret");
    }

    private void login(String username, String password) {
        driver.findElement(By.name("user")).sendKeys(username);
        driver.findElement(By.name("pass")).sendKeys(password);
        driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    }

    @Test
    public void testGroupCreation() {
        gotoGroupPage();
        initGroupCreation("new");
        initGroupCreation("group_name");
        fillGroupForm(new GroupData("test1", "test2", "test3"));
        submitGroupCreation("submit");
        returnToGroupPage(By.linkText("groups"));
    }

    private void gotoGroupPage() {
        driver.findElement(By.linkText("groups")).click();
    }

    private void initGroupCreation(String s) {
        driver.findElement(By.name(s)).click();
    }

    private void fillGroupForm(GroupData groupData) {
        driver.findElement(By.name("group_name")).sendKeys(groupData.getName());
        driver.findElement(By.name("group_header")).sendKeys(groupData.getHeader());
        driver.findElement(By.name("group_footer")).sendKeys(groupData.getFooter());
    }

    private void submitGroupCreation(String submit) {
        driver.findElement(By.name(submit)).click();
    }

    private void returnToGroupPage(By groups) {
        driver.findElement(groups).click();
    }

    @After
    public void tearDown() {
        driver.quit();
    }
}
